<html>
	<head>
		<title>  Artes Gigatônicas </title>
	</head>
	
	<body bgcolor="FFCC99" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
		<table width="100%" border="1" cellspacing="0" cellpadding="0"> 
			<tr> <center> <img src="\TPII50\PASTA DAORA\imagens\superior.jpg" width="640" height="66"> </center> </td>
			</tr>
			<tr>
				<td width=10% height=30%> <!--#Include File ="menu.ASP"--> </td>
				<td> <!--#Include File ="link.ASP"--> </td>
			</tr>				 
		</table>
	</body>
</html>